name: Website Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allow manual runs

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10     # Prevent hanging jobs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests playwright
        playwright install chromium

    - name: Run monitor script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python check_site.py  # Replace with your actual script name

    - name: Upload debug artifacts
      if: ${{ always() }}  # Run even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: debug-files
        path: |
          screenshot.png
          output.html
